on:
  push:
    # delete this item if you don't want to trigger this workflow when modify this repo
    branches: master
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 0 * * *'
name: Mirror GitHub Repos to Gitee
jobs:
  run:
    name: Sync-GitHub-to-Gitee
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v1
    - name: Mirror the Github organization repos to Gitee.
      uses: Yikun/hub-mirror-action@master
      with:
        src: github/ShixiangWang
        dst: gitee/ShixiangWang
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        force_update: true
